modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/dimadencep/RemoveReloadingScreen/issues"
license = "AGPL-3.0-or-later"

[[mods]]
modId = "rrls"
version = "${version}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/rrls"
displayName = "Remove Reloading Screen"
authors = "dima_dencep"
description = "Removes the resources reload screen, and leaves the game available"
logoFile = "icon.png"

[[dependencies.rrls]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rrls]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rrls]]
modId = "cloth_config"
mandatory = true
versionRange = "[6.4.90,)"
ordering = "NONE"
side = "CLIENT"