modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/dimadencep/RemoveReloadingScreen/issues"
license = "AGPL-3.0-or-later"

[[mods]]
modId = "rrls"
version = "${mod_version}"
displayURL = "https://modrinth.com/mod/rrls"
displayName = "Remove Reloading Screen"
authors = "dima_dencep"
description = "Removes the resources reload screen, and leaves the game available"
logoFile = "icon.png"
displayTest = "IGNORE_SERVER_VERSION"

[[dependencies.rrls]]
modId = "forge"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.rrls]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rrls]]
modId = "cloth_config"
mandatory = true
versionRange = "[${cloth_config_version},)"
ordering = "NONE"
side = "CLIENT"