modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/dimadencep/RemoveReloadingScreen/issues"
license = "AGPL-3.0-or-later"

[[mods]]
modId = "rrls"
version = "${version}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/rrls"
displayName = "Remove Reloading Screen"
authors = "dima_dencep"
description = "Removes the resources reload screen, and leaves the game available"
logoFile = "icon.png"

[[dependencies.rrls]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rrls]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rrls]]
modId = "cloth-config"
mandatory = true
versionRange = "[4.16.91,)"
ordering = "NONE"
side = "CLIENT"