modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/dimadencep/RemoveReloadingScreen/issues"
license = "AGPL-3.0-only"

[[mods]]
modId = "rrls"
version = "${version}"
displayURL = "https://modrinth.com/mod/rrls"
displayName = "Remove Reloading Screen"
updateJSONURL = "https://api.modrinth.com/updates/rrls/forge_updates.json"
authors = "dima_dencep"
description = "Removes the resources reload screen, and leaves the game available"
logoFile = "icon.png"

[[dependencies.rrls]]
modId = "forge"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.rrls]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rrls]]
modId = "cloth_config"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "CLIENT"