modLoader = "javafml"
loaderVersion = "[45,)"
issueTrackerURL = "https://github.com/dimadencep/RemoveReloadingScreen/issues"
license = "AGPL-3.0-or-later"

[[mods]]
modId = "rrls"
version = "${version}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/rrls"
displayName = "Remove Reload Screen"
authors = "dima_dencep"
description = "Removes the resources reload screen, and leaves the game available"
logoFile = "icon.png"

[[dependencies.rrls]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rrls]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rrls]]
modId = "cloth_config"
mandatory = true
versionRange = "[8.2.88,)"
ordering = "NONE"
side = "CLIENT"