name: Publish Release

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Upload assets to releases
        run: ./gradlew build

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Read value from Properties-file
        id: read_property
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: './gradle.properties'
          properties: 'archives_base_name mod_version minecraft_version cloth_config_version'

      - name: Publish Forge to Modrinth & CurseForge
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: ZP7xHXtw
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 833233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          
          files-primary: forge/build/libs/!(*-@(dev|sources|javadoc|shadow)).jar
          files-secondary: forge/build/libs/*-@(dev|sources|javadoc).jar

          name: RemoveReloadingScreen ${{ steps.read_property.outputs.mod_version }} Forge for Minecraft ${{ steps.read_property.minecraft_version.mod_version }}

          changelog: ${{steps.build_changelog.outputs.changelog}}

          version-type: beta

          loaders: forge

          game-versions: |
            1.19.4
          
          dependencies: |
            cloth-config | includes | 9.0.94
            
          java: |
            17
            
      - name: Publish Fabric to Modrinth & CurseForge
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: ZP7xHXtw
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 833233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          
          files-primary: fabric/build/libs/!(*-@(dev|sources|javadoc|shadow)).jar
          files-secondary: fabric/build/libs/*-@(dev|sources|javadoc).jar

          name: RemoveReloadingScreen ${{ steps.read_property.outputs.mod_version }} Fabric for Minecraft ${{ steps.read_property.minecraft_version.mod_version }}

          changelog: ${{steps.build_changelog.outputs.changelog}}

          version-type: beta

          loaders: fabric

          game-versions: |
            1.19.4
          
          dependencies: |
            fabric-api | depends | *
            cloth-config | includes | 9.0.94
            modmenu | recommends | *
            
          java: |
            17

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          artifacts: "forge/build/libs/*.jar,fabric/build/libs/*.jar"
          name: ${{ github.ref_name }}
          body: ${{steps.build_changelog.outputs.changelog}}
          token: ${{ secrets.GITHUB_TOKEN }}