name: Publish Release

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Upload assets to releases
        run: ./gradlew build

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          failOnError: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Read value from Properties-file
        id: read_property
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: './gradle.properties'
          properties: 'archives_base_name mod_version minecraft_version cloth_config_version'

      - name: Publish Forge to Modrinth & CurseForge
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: ZP7xHXtw
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 833233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          
          files-primary: forge/build/libs/!(*-@(dev|sources|javadoc|shadow)).jar
          files-secondary: forge/build/libs/*-@(dev|sources|javadoc).jar

          name: ${{ steps.read_property.outputs.archives_base_name }} ${{ steps.read_property.outputs.mod_version }} Forge ${{ steps.read_property.outputs.minecraft_version }}

          changelog: ${{steps.build_changelog.outputs.changelog}}

          version-type: release

          loaders: forge

          game-versions: |
            ${{ steps.read_property.outputs.minecraft_version }}
          
          dependencies: |
            cloth-config | depends | ${{ steps.read_property.outputs.cloth_config_version }}
            
          java: |
            17
            11
            8
            
      - name: Publish Fabric to Modrinth & CurseForge
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: ZP7xHXtw
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 833233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          
          files-primary: fabric/build/libs/!(*-@(dev|sources|javadoc|shadow)).jar
          files-secondary: fabric/build/libs/*-@(dev|sources|javadoc).jar

          name: ${{ steps.read_property.outputs.archives_base_name }} ${{ steps.read_property.outputs.mod_version }} Fabric ${{ steps.read_property.outputs.minecraft_version }}

          changelog: ${{steps.build_changelog.outputs.changelog}}

          version-type: release

          loaders: fabric

          game-versions: |
            ${{ steps.read_property.outputs.minecraft_version }}
          
          dependencies: |
            fabric-api | depends | *
            cloth-config | includes | ${{ steps.read_property.outputs.cloth_config_version }}
            modmenu | recommends | *
            
          java: |
            17
            11
            8

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.read_property.outputs.minecraft_version }}-${{ steps.read_property.outputs.mod_version }}"
          prerelease: false
          title: "${{ steps.read_property.outputs.archives_base_name }} ${{ steps.read_property.outputs.mod_version }}"
          files: |
            fabric/build/libs/*
            forge/build/libs/*