name: Publish Release

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Upload assets to releases
        run: ./gradlew build

      - name: Publish Forge to Modrinth & CurseForge
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: ZP7xHXtw
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 833233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
          files-primary: forge/build/libs/!(*-@(dev|sources|javadoc|shadow)).jar
          files-secondary: forge/build/libs/*-@(dev|sources|javadoc).jar

          version-type: release

          loaders: forge

          game-versions: |
            1.19.3
          
          dependencies: |
            cloth-config | includes | 9.0.94
            
          java: |
            17
            
      - name: Publish Fabric to Modrinth & CurseForge
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: ZP7xHXtw
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 833233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
          files-primary: fabric/build/libs/!(*-@(dev|sources|javadoc|shadow)).jar
          files-secondary: fabric/build/libs/*-@(dev|sources|javadoc).jar

          version-type: release

          loaders: fabric

          game-versions: |
            1.19.3
          
          dependencies: |
            fabric-api | depends | *
            cloth-config | includes | 9.0.94
            
          java: |
            17
