name: Publish Release

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Upload assets to releases
        run: ./gradlew build

      - name: Get previous tag
        id: previousTag
        run: |
          name=$(git --no-pager tag --sort=creatordate --merged ${{ github.ref_name }} | tail -2 | head -1)
          echo "previousTag: $name"
          echo "previousTag=$name" >> $GITHUB_ENV

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ github.ref_name }}
          toTag: ${{ env.previousTag }}
          writeToFile: false

      - name: Read value from Properties-file
        id: read_property
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: './gradle.properties'
          properties: 'archives_base_name mod_version minecraft_version cloth_config_version'

      - name: Publish Forge to Modrinth & CurseForge
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: ZP7xHXtw
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 833233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          
          files-primary: forge/build/libs/!(*-@(dev|sources|javadoc|shadow)).jar
          files-secondary: forge/build/libs/*-@(dev|sources|javadoc).jar

          name: RemoveReloadingScreen ${{ steps.read_property.outputs.mod_version }} Forge for Minecraft ${{ steps.read_property.minecraft_version.mod_version }}

          changelog: ${{ steps.changelog.outputs.changes }}

          version-type: beta

          loaders: forge

          game-versions: |
            1.19.4
          
          dependencies: |
            cloth-config | includes | 9.0.94
            
          java: |
            17
            
      - name: Publish Fabric to Modrinth & CurseForge
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: ZP7xHXtw
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 833233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          
          files-primary: fabric/build/libs/!(*-@(dev|sources|javadoc|shadow)).jar
          files-secondary: fabric/build/libs/*-@(dev|sources|javadoc).jar

          name: RemoveReloadingScreen ${{ steps.read_property.outputs.mod_version }} Fabric for Minecraft ${{ steps.read_property.minecraft_version.mod_version }}

          changelog: ${{ steps.changelog.outputs.changes }}

          version-type: beta

          loaders: fabric

          game-versions: |
            1.19.4
          
          dependencies: |
            fabric-api | depends | *
            cloth-config | includes | 9.0.94
            modmenu | recommends | *
            
          java: |
            17

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          artifacts: "forge/build/libs/*.jar,fabric/build/libs/*.jar"
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ secrets.GITHUB_TOKEN }}